"""classified_area.classified_as now named classified_area.tag

Revision ID: 1f680a28d58d
Revises: e0bea9cc2b6c
Create Date: 2020-11-03 19:57:57.607105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f680a28d58d'
down_revision = 'e0bea9cc2b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classified_area', sa.Column('tag', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_classified_area_tag'), 'classified_area', ['tag'], unique=False)
    op.drop_index('ix_classified_area_classified_as', table_name='classified_area')
    op.drop_column('classified_area', 'classified_as')
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('classified_area', sa.Column('classified_as', sa.VARCHAR(length=256), nullable=True))
    op.create_index('ix_classified_area_classified_as', 'classified_area', ['classified_as'], unique=False)
    op.drop_index(op.f('ix_classified_area_tag'), table_name='classified_area')
    op.drop_column('classified_area', 'tag')
    # ### end Alembic commands ###
