"""Added classified images table

Revision ID: 39557dc00aeb
Revises: 7c8f37ceba36
Create Date: 2020-11-02 18:25:53.433998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39557dc00aeb'
down_revision = '7c8f37ceba36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('classified_as', sa.String(length=256), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['training_image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_area_classified_as'), 'classified_area', ['classified_as'], unique=False)
    op.create_index(op.f('ix_classified_area_public_id'), 'classified_area', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_area_public_id'), table_name='classified_area')
    op.drop_index(op.f('ix_classified_area_classified_as'), table_name='classified_area')
    op.drop_table('classified_area')
    # ### end Alembic commands ###
