"""Crated Users table and TraningImage table

Revision ID: 429cf99b68ff
Revises: 
Create Date: 2020-11-02 18:06:10.937637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429cf99b68ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=248), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_public_id'), 'user', ['public_id'], unique=True)
    op.create_table('training_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_image_image_url'), 'training_image', ['image_url'], unique=False)
    op.create_index(op.f('ix_training_image_public_id'), 'training_image', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_image_public_id'), table_name='training_image')
    op.drop_index(op.f('ix_training_image_image_url'), table_name='training_image')
    op.drop_table('training_image')
    op.drop_index(op.f('ix_user_public_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
